### ISSUE TITLE
Add a filter that only shows franchises that have a film in the last decade

### ISSUE THREAD

**Issue by Robson** [Robson/Film-Franchise-Ratings#7]
This would be entirely done within index.html

**Step 1**
Add something like `<option value="recentfilm">Franchises with a film within the last decade</option>` to the `controls_filter` select (line 45).

**Step 2**
Add a new case within `showCharts` in the `selectedFilter` switch (line 255), which filters `sortedFilms` down to just the franchises that have a film within the last decade. Ideally this would be dynamic (e.g. if the current year is 2025, it would show franchises that have a film that was released in 2016 or later).

I should note here that `sortedFilms` is quite a bad name, because it's actually the sorted franchises.

**Comment by Neox63** [comment]
I'm on it ! :)

**Comment by Neox63** [comment]
Done !

**Comment by Robson** [comment]
Thank you Neox63! Very kind of you to contribute.

I think I wasn't completely clear about how this should work. The filter should just show franchises that have a film (i.e. any film, not the first film) in the last decade. So it's essentially showing the franchises that are active now, regardless of when they started.

For example, the Mad Max franchise would be included. This started in 1979, but the most recent film came out in 2015, so that's within the last decade rule. (Although I appreciate that 2015 feels like a lot longer ago!)

Your code is very close to doing that, despite my ambiguity. You would just need to:

- Step 1. Instead of "Franchises that started in the last decade" you would want something like "Franchises with a film within the last decade".
- Step 2. Adapt your filter rule to be along the lines of:
`sortedFilms = sortedFilms.filter(a => a.Films[a.Films.length - 1].Year > new Date(Date.now()).getFullYear() - 10);`

Films are always ordered chronologically, so it's safe to just look at the most recent film.

**Comment by Neox63** [comment]
Okay ! No problem ! Doing the change and I'll update the pull request ! :)

**Comment by Neox63** [comment]
Here we go, it's done, tell me if you want me to change something else :)

I'm trying to start contributing to projects, making some PR, solving issues etc... This is pretty new for me, don't hesitate to tell me if i'm doing something wrong !

**Comment by Robson** [comment]
That's perfect!

Thank you very much for your contribution. I think you've done this all exactly as pull-requests/issues should be done. I appreciate the linking of the pull-request and issue as well.

I've merged that into the master and it's live now.
